import type { Metadata } from "next";

import { ModalProvider } from "@/contexts/ModalContext";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ModalProvider>{children}</ModalProvider>
      </body>
    </html>
  );
}
